### ISSUE TITLE
Prefetch gets all messages in the queue

### ISSUE THREAD

**Issue by marcbrisson** [bidossessi/dramatiq-azure#1]
Hi, 

thanks for sharing this project. 

I was wondering why when you prefetch messages you read all the message pages... and end up reading all the messages in the queue.

https://github.com/bidossessi/dramatiq-azure/blob/94151414dda670d548b14f9d9c0596b3143cd1a1/dramatiq_azure/asq.py#L133

As you have a MAXPREFETCH of 32 this mean at most one page of the q_client.receive_messages pager.

I you use 

msg_batch = [item for item in next(pager.by_page())]

instead of 

msg_batch = [item for sublist in pager.by_page() for item in sublist]

This limits to reading only the first page.

Thanks again

**Comment by bidossessi** [comment]
@marcbrisson Nice catch. Would you be willing to make a PR?

**Comment by marcbrisson** [comment]
Yes, I'm working on it

**Comment by bidossessi** [comment]
@marcbrisson https://opensource.com/article/19/7/create-pull-request-github

**Comment by bidossessi** [comment]
closed by #2
